from pydantic import BaseModel, ConfigDict
from typing import Optional


class TrafficDataResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    year: Optional[int]
    region_id: Optional[int]
    cars_and_taxis: Optional[int]
    buses_and_coaches: Optional[int]
    lgvs: Optional[int]
    hgvs_2_rigid_axle: Optional[int]
    hgvs_3_rigid_axle: Optional[int]
    hgvs_4_or_more_rigid_axle: Optional[int]
    hgvs_3_or_4_articulated_axle: Optional[int]
    hgvs_5_articulated_axle: Optional[int]
    hgvs_6_articulated_axle: Optional[int]
    all_hgvs: Optional[int]
    all_motor_vehicles: Optional[int]
    count_point_id: Optional[int]
    local_authority_id: Optional[int]
    easting: Optional[int]
    northing: Optional[int]
    latitude: Optional[float]
    longitude: Optional[float]
    link_length_km: Optional[float]
    link_length_miles: Optional[float]
    pedal_cycles: Optional[int]
    two_wheeled_motor_vehicles: Optional[int]
    region_name: Optional[str]
    region_ons_code: Optional[str]
    direction_of_travel: Optional[str]
    local_authority_name: Optional[str]
    local_authority_code: Optional[str]
    road_name: Optional[str]
    road_category: Optional[str]
    road_type: Optional[str]
    start_junction_road_name: Optional[str]
    end_junction_road_name: Optional[str]
    estimation_method: Optional[str]
    estimation_method_detailed: Optional[str]
